{% set version = "4.3" %}
{% set sha256 = "8afd0d7f47cf2bccf1b71dd223b4864e581f1a1871f85e0f4f502d891b1c42a4" %}

package:
  name: cat
  version: {{ version }}

source:
  url: https://github.com/dutilh/CAT/archive/v{{ version }}.tar.gz # [linux]
  sha256: {{ sha256 }}  # [linux]

build:
  number: 1

requirements:
  run:
    - python=3
    - diamond
    - prodigal

test:
  commands:
    - CAT prepare --help


about:
  summary: |
    CAT/BAT: tool for taxonomic classification of contigs and metagenome-assembled genomes (MAGs)
  home: https://github.com/dutilh/CAT
  license: "CC BY 3.0"
