{% set version = "4.2" %}
{% set sha256 = "72e8e84712667eac4ceced23955551c96374ba7b66eca19960bc2c6a2510a388" %}

package:
  name: cat
  version: {{ version }}

source:
  url: https://github.com/dutilh/CAT/archive/v{{ version }}.tar.gz # [linux]
  sha256: {{ sha256 }}  # [linux]

build:
  number: 1

requirements:
  run:
    - python=3
    - diamond
    - prodigal

test:
  commands:
    - CAT prepare --help


about:
  summary: |
    CAT/BAT: tool for taxonomic classification of contigs and metagenome-assembled genomes (MAGs)
  home: https://github.com/dutilh/CAT
  license: "CC BY 2.0"
