package:
  name: interproscan
  version: "5.31.70.0"

source:
  url: ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.31-70.0/interproscan-5.31-70.0.0-64-bit.tar.gz
  md5: "3caadabcb2c305025a9135d9cf928c00"
# panther db
#  url: ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/data/panther-data-12.0.tar.gz
#  md5: f2edbfe055040708e801231cb371a292

build:
  number: 1
  skip: True  # [not linux]

requirements:
  host:
    - python=3.6
    - perl=5.26
    - java-jdk=8

  run:
    - python=3.6
    - perl=5.26
    - java-jdk=8

test:
  commands:
    - "interproscan.sh -h|| [[ $? == 1 ]] "

about:
  home: https://www.ebi.ac.uk/interpro/search/sequence-search
  license: Apache License, Version 2.0
