{% set version = "2.0.1" %}

package:
  name: genome-properties
  version: {{ version }}

source:
  url: https://github.com/SilasK/genome-properties/archive/v{{ version }}.tar.gz
  sha256: 628428e7ed2b74c16703fcf8e825e84d4cbcbadf4dc61dac6c64e89f35694ecc
build:
  number: 1

requirements:
  host:
    - perl=5.22.0.1
    - perl-app-cpanminus=1.7043
    - perl-clone=0.38
    - perl-json=2.90
    - perl-try-tiny=0.24
  run:
    - perl=5.22.0.1
    - perl-app-cpanminus=1.7043
    - perl-clone=0.38
    - perl-json=2.90
    - perl-try-tiny=0.24

test:
  commands:
    - assign_genome_properties.pl -h

about:
  home: https://www.ebi.ac.uk/interpro/genomeproperties/
  license: GPLv3
  license_family: GPL
  summary: |
    Genome properties is an annotation system whereby functional attributes can be assigned to a genome, based on the presence of a defined set of protein signatures within that genome. Properties (which often describe pathways) are composed of steps, with each step defining a protein required for the function of the pathway/property. Genome properties use protein signatures as evidence to determine the presence of each step within a property.
  dev_url: https://github.com/ebi-pf-team/genome-properties
  doc_url: https://genome-properties.readthedocs.io/en/latest/index.html
extra:
  recipe-maintainers:
    - kiesers
  identifiers:
    - doi:10.1093/nar/gky1013
